### PR TITLE
Add support for baremetal programming.

### PR DESCRIPTION
**Pull request by winksaville**
Add support for generating "pool = console" by specifying
a pool kwarg for Target.

Add support for defining a prog for a compiler.

Add support for obj_copy and run_target targets.

### CODE REVIEW

**Comment by winksaville** [comment]
Niklas,

Here is a hack that allows me to use craftr to cross compile [baremetal-hi](https://github.com/winksaville/baremetal-hi/tree/add-support-for-craftr). Hopefully there is something you can use.

There is one additional item needed, we need to generate a line "default test.bin" so that executing "ninja" with no parameters creates test.bin and then "ninja run" to run the test.bin.

Let me know what you think.

**Comment by NiklasRosenstein** [comment]
Hey Wink, I was trying to rebase the commit but I can't get it back onto your repo so I made a [baremetal-support](https://github.com/craftr-build/craftr/tree/baremetal-support) branch that contains your commit. Thanks for the contribution! Could you give me a short glimpse on how you were planning to use the `obj_copy()` and `run_target()` functions?

Thanks! I will also find a good way to declare a default target, currently running `ninja` without arguments will just build everything.

**Comment by winksaville** [comment]
Look at Craftrfile in baremetal-hi. I'll rebase it when I get up.

**Comment by NiklasRosenstein** [comment]
Oh, I missed there is one in the repository. Thanks! I'll probably make some minor changes to the interface, just so you know that you might need to adapt the Craftfile. Eg. I would rename the `obj_copy` to `objcopy`(since that's the name of the GNU tool) and I would make `objcopy()` work similarly to the `objects()` function in that it will work with multiple input/output pairs, like

```python
cxx.objcopy(
  prog = 'arm-eabi-objcopy',
  inputs = [objects],
  outputs = addsuffix(rmvsuffix(objects), '.bin'),
  additional_flags = ['-O', 'binary'],
)
```

There just needs to be an output file for each input file. (Note for the snippet above: Currently a `Target` is not iterable, but it will soon bee. See #16.

**Comment by NiklasRosenstein** [comment]
Also, I will move the `run_target()` away from the compiler modules as it has nothing to do with them. I will make it into another module or maybe a built-in that is always available.

**Comment by winksaville** [comment]
SG, I tired compiling startup.S and test.c with one compiler but I couldn't
get it to work, it didn't create the multiple output files correct IIRC.
(Note I've rebased the pull request, although there were no conflicts and I
don't understand why you couldn't do it).

**Comment by winksaville** [comment]
Another Hack I did was "prog". You've got a "program" variable defined and
initialized but its not used and instead you used "lang" to generate the
program name. I suspect there's a better way to implement that, there be
prog and program. I think prog should set program and if not set then the
"automatic" determination should occur, or some such.

**Pull request closed without merging**
